/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package funciones_lambda

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}
fun main() {
    var productos=ArrayList<Producto>()
        productos.add(Producto("Lavadora grande",345f ,"lg.jpeg","lavadora grande",Estado.ACTIVO))
        productos.add(Producto("Televisor 55\"",545f ,"tv55.jpeg","televisor grande",Estado.ACTIVO))
        productos.add(Producto("Portatil 14",654f ,"ptt.jpeg","portatil de 8gb pequeño",Estado.ACTIVO))

    var portatiles = Categoria ("Portatiles", Estado.ACTIVO, "imagenportatil.jpg")

        portatiles.producto.add(
            Producto("Lisa", 100f, "lisa.jpeg", "Uno de los primeros ordenadores de Apple.", Estado.ACTIVO)
        )
        portatiles.producto.add(
            Producto("IBMPC", 50f, "ibmpc.jpeg", "El primer equipo para el gran público.", Estado.ACTIVO)
        )

    var impresoras = Categoria ("Impresoras", Estado.ACTIVO, "imagenimpresora.jpg")

        impresoras.producto.add(
            Producto("Brother Colo1234", 10f, "brother.jpeg", "Impresora a color.", Estado.ACTIVO)
        )
        impresoras.producto.add(
            Producto("HP Laser", 20f, "hp.jpeg", "Impresora laser.", Estado.ACTIVO)
        )
    var categorias: HashMap<String, ArrayList<Producto>> = HashMap()
    categorias.put("portatiles", portatiles.producto)
    categorias.put("impresoras", impresoras.producto)

    categorias.keys.forEach { println("La lista de categorias son: "+ it) }

    categorias["portatiles"]?.forEach { println(it.nombre) }

    categorias.keys.forEach { println("Volver a listar las categorias: "+ it) }

    var todosLosProductos = ArrayList<Producto>()
    todosLosProductos.addAll(productos)
    todosLosProductos.addAll(portatiles.producto)
    todosLosProductos.addAll(impresoras.producto)

    var precioMedio = todosLosProductos.map { it.precio }.average()


    println("El precio medio de los productos es: $precioMedio €")


}





